version: '3'

networks:
  transcendence-network:
    name: transcendence-network

services:
  postgresql:
    image: postgres:15.5-alpine3.18
    container_name: postgresql
    networks:
      - transcendence-network
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB_NAME: "${POSTGRES_DB_NAME}"
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${DB_PATH}"
