version: '3'

services:
  postgresql:
    image: postgres:15.5-alpine3.18
    environment:
      POSTGRES_PASSWORD: prueba
      POSTGRES_USER: prueba
    restart: on-failure
    ports:
      - "9000:5432"


volumes:
  database:
    external: true
      


