# Generated by Django 4.2 on 2023-12-22 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerFriend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('registerDate', models.DateField(auto_now_add=True)),
                ('myFriend', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_friend', to=settings.AUTH_USER_MODEL)),
                ('myUser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
